# conda env create --file environment.yml
# mamba env create --file environment.yml
name: research-on-argentina
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - missingno
  - nbdime
  - numpy
  - pandas
  - pip
  - plotly
  - pyjanitor
  - pyprojroot
  - python=3.11.5
  - seaborn
  - session-info
  - upsetplot
  